version: "3.6"
services:
  sonarr:
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    image: lscr.io/linuxserver/sonarr:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr.entrypoints: https
      traefik.http.routers.sonarr.middlewares: authelia@docker,internal-ipallowlist@docker
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - traefik
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/sonarr/config:/config
      - ${DATA_DIR}/data:/data
networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
