version: "3.6"
services:
  readarr:
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    image: lscr.io/linuxserver/readarr:develop
    labels:
      traefik.enable: "true"
      traefik.http.routers.readarr.entrypoints: https
      traefik.http.routers.readarr.middlewares: authelia@docker,internal-ipallowlist@docker
      traefik.http.services.readarr.loadbalancer.server.port: "8787"
    networks:
      - traefik
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/readarr/config:/config
      - ${DATA_DIR}/data:/data
networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
