version: "3.6"
services:
  prowlarr:
    container_name: "prowlarr"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: "lscr.io/linuxserver/prowlarr:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.prowlarr.entrypoints: "https"
      traefik.http.routers.prowlarr.middlewares: "authelia@docker,internal-ipallowlist@docker"
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
    networks:
      - "traefik"
    restart: "unless-stopped"
    volumes:
      - "${DATA_DIR}/prowlarr/config:/config"
networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
