version: "3.6"
services:
  code:
    container_name: "code"
    environment:
      #- "DOCKER_MODS=linuxserver/mods:universal-package-install|linuxserver/mods:code-server-golang|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-extension-arguments"
      #- "HOME=/config"
      #- "INSTALL_PACKAGES_FYNE_CROSS_COMPILE=gcc-mingw-w64-x86-64|libgl1-mesa-dev|xorg-dev"
      - "PGID=${PGID}"
      - "PUID=${PUID}"
      - "SUDO_PASSWORD=${CODE_SUDO_PASS}"
      - "TZ=${TZ}"
      #- "VSCODE_EXTENSION_IDS=rust-lang.rust"
      - "PROXY_DOMAIN=code.${BASE_DOMAIN}"
    image: "lscr.io/linuxserver/code-server:latest" # 4.9.0 works
    ipc: "private"
    labels:
      traefik.enable: "true"
      traefik.http.routers.code.entrypoints: https
      traefik.http.routers.code.middlewares: "authelia@docker"
      traefik.http.services.code.loadbalancer.server.port: 8443
    networks:
      - "traefik"
    restart: "unless-stopped"
    volumes:
      - "${DATA_DIR}/code/init:/custom-cont-init.d:ro"
      - "${DATA_DIR}/code/projects:/projects"
      - "${DATA_DIR}/code/config:/config"
networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
