version: "3.6"
services:
  plex:
    container_name: "plex"
    environment:
      - "VERSION=docker"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: "ghcr.io/linuxserver/plex:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.plex.entrypoints: "https"
      traefik.http.services.plex.loadbalancer.server.port: "32400"
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - "traefik"
    ports:
      - "32400:32400/tcp"
    restart: "unless-stopped"
    volumes:
      - "${DATA_DIR}/data/media:/data/media"
      - "${DATA_DIR}/plex/config:/config"
  tautulli:
    container_name: "tautulli"
    environment:
      - "TZ=${TZ}"
      - "PGID=${PGID}"
      - "PUID=${PUID}"
    image: "tautulli/tautulli:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.tautulli.entrypoints: "https"
      traefik.http.services.tautulli.loadbalancer.server.port: "8181"
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - "traefik"
    restart: "unless-stopped"
    volumes:
      - "${DATA_DIR}/tautulli:/config"
networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
