version: "3.6"
services:
  shlink:
    container_name: "shlink"
    environment:
      - "TIMEZONE=${TZ}"
      - "DEFAULT_DOMAIN=goto.${BASE_DOMAIN}"
      - "IS_HTTPS_ENABLED=true"
      - "DB_PASSWORD=${SHLINK_DB_PASSWORD}"
      - "DB_USER=${SHLINK_DB_USER}"
      - "DB_NAME=${SHLINK_DB_NAME}"
      - "DB_HOST=${SHLINK_DB_HOST}"
      - "DB_DRIVER=postgres"
    image: "shlinkio/shlink:stable-roadrunner"
    labels:
      traefik.enable: "true"
      traefik.http.routers.shlink.entrypoints: "https"
      traefik.http.routers.shlink.rule: "Host(`goto.${BASE_DOMAIN}`)"
      traefik.http.services.shlink.loadbalancer.server.port: "8080"
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - "traefik"
    restart: "unless-stopped"
  shlink-ui:
    depends_on:
      - shlink
    container_name: "shlink-ui"
    environment:
      - "TZ=${TZ}"
      - "SHLINK_SERVER_API_KEY=${SHLINK_API_KEY}"
      - "SHLINK_SERVER_URL=https://goto.${BASE_DOMAIN}"
    image: "shlinkio/shlink-web-client:3.8.1"
    labels:
      traefik.enable: "true"
      traefik.http.routers.shlink-ui.entrypoints: "https"
      traefik.http.routers.shlink-ui.middlewares: "authelia@docker"
      traefik.http.routers.shlink-ui.rule: "Host(`shlink.${BASE_DOMAIN}`)"
      traefik.http.services.shlink-ui.loadbalancer.server.port: "80"
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - "traefik"
    restart: "unless-stopped"
networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
