version: "3.6"
services:
  homeassistant:
    container_name: "homeassistant"
    devices:
      - "/dev/serial/by-id/${ZIGBEE_DEVICE_ID}:/dev/zigbee"
    environment:
      - "PGID=${PGID}"
      - "PUID=${PUID}"
      - "TZ=${TZ}"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    labels:
      traefik.enable: "true"
      traefik.http.routers.homeassistant.entrypoints: "https"
      traefik.http.routers.homeassistant.rule: "Host(`ha.${BASE_DOMAIN}`)"
      traefik.http.services.homeassistant.loadbalancer.server.port: "8123"
    network_mode: "host"
    restart: "unless-stopped"
    volumes:
      - "${DATA_DIR}/homeassistant/config:/config"
      - "${DATA_DIR}/homeassistant/media:/media/files"
