version: "3.6"
services:
  homeassistant:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    container_name: "homeassistant"
    entrypoint:
      - "/init"
    environment:
      - "HOME=/config"
      - "LSIO_FIRST_PARTY=true"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PGID=998"
      - "PIPFLAGS=--no-cache-dir --use-deprecated=legacy-resolver --find-links https://wheel-index.linuxserver.io/alpine-3.16/\
        \ --find-links https://wheel-index.linuxserver.io/homeassistant-3.16/"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$"
      - "PUID=1000"
      - "PYTHONPATH=:/pip-packages"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "S6_VERBOSITY=1"
      - "TERM=xterm"
      - "TZ=America/Denver"
      - "VIRTUAL_ENV=/lsiopy"
      - "PIP_DISABLE_PIP_VERSION_CHECK=1"
      - "LANG=C.UTF-8"
      - "S6_BEHAVIOUR_IF_STAGE2_FAILS=2"
      - "S6_CMD_WAIT_FOR_SERVICES=1"
      - "S6_SERVICES_READYTIME=50"
      - "WHEELS_LINKS=https://wheels.home-assistant.io/musllinux/"
      - "S6_SERVICES_GRACETIME=220000"
    hostname: "pixelblue"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ipc: "private"
    labels:
      build_version: "Linuxserver.io version:- 2022.11.3-ls109 Build-date:- 2022-11-17T15:20:54+01:00"
      com.docker.compose.config-hash: "a8268f471211e4724a17f761c60e33ac938017a2d866645985071c9559dc4b15"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:d52b6bb8e97bf50692c7d8bd8f171f401491c31eb29b2afc261e5879449972df"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "main"
      com.docker.compose.project.config_files: "/data/compose/1/docker-compose.yml"
      com.docker.compose.project.working_dir: "/data/compose/1"
      com.docker.compose.service: "homeassistant"
      com.docker.compose.version: "2.10.2"
      io.hass.arch: "amd64"
      io.hass.base.arch: "amd64"
      io.hass.base.image: "ghcr.io/home-assistant/amd64-base:3.18"
      io.hass.base.name: "python"
      io.hass.base.version: "2023.09.0"
      io.hass.type: "core"
      io.hass.version: "2023.10.1"
      maintainer: "saarg, roxedus"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2022-11-17T15:20:54+01:00"
      org.opencontainers.image.description: "[Home Assistant Core](https://www.home-assistant.io/)\
        \ - Open source home automation that puts local control and privacy first.\
        \ Powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect\
        \ to run on a Raspberry Pi or a local server.   "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-homeassistant"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "54db093c95bb618413dcd7569244443ed92afe78"
      org.opencontainers.image.revision: "54db093c95bb618413dcd7569244443ed92afe78"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-homeassistant"
      org.opencontainers.image.title: "Homeassistant"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-homeassistant/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "2022.11.3-ls109"
      traefik.enable: "true"
      traefik.http.routers.homeassistant.entrypoints: "https"
      traefik.http.routers.homeassistant.rule: "Host(`ha.pixelrazor.tech`)"
      traefik.http.services.homeassistant.loadbalancer.server.port: "8123"
    logging:
      driver: "json-file"
      options: {}
    network_mode: "host"
    restart: "unless-stopped"
    volumes:
      - "/opt/appdata/homeassistant/config:/config"
      - "/opt/appdata/homeassistant/media:/media/files"
    working_dir: "/"
