version: "3.6"
services:
  radarr:
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    image: lscr.io/linuxserver/radarr:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr.entrypoints: https
      traefik.http.routers.radarr.middlewares: authelia@docker,internal-ipallowlist@docker
      traefik.http.services.radarr.loadbalancer.server.port: "7878"
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - traefik
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/radarr/config:/config
      - ${DATA_DIR}/data:/data
networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
