version: "3.6"
services:
  uptime-kuma:
    container_name: "uptime-kuma"
    environment:
      - "TZ=${TZ}"
      - "PGID=${PGID}"
      - "PUID=${PUID}"
    image: "louislam/uptime-kuma:1"
    labels:
      traefik.enable: "true"
      traefik.http.routers.uptime-kuma.entrypoints: "https"
      traefik.http.routers.uptime-kuma.rule: "Host(`uptime.${BASE_DOMAIN}`)"
      traefik.http.services.uptime-kuma.loadbalancer.server.port: "3001"
    networks:
      - "traefik"
    restart: "unless-stopped"
    volumes:
      - "${DATA_DIR}/uptimekuma/data:/app/data"
networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
