version: "3.6"
services:
  portainer:
    container_name: "portainer"
    image: "portainer/portainer-ce:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: https
      traefik.http.routers.portainer.middlewares: "internal-ipallowlist@docker" 
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    networks:
      - "traefik"
    restart: "always"
    volumes:
      - "${DATA_DIR}/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}
